num1 = int(input("enter the number:"))
num2 = int(input("enter the number:"))
sum= float(num1)+float(num2)
print('the sum of {0} and {1} is {2}'.format(num1, num2, sum))
sub= float(num1)-float(num2)
print('the sub of {0} and {1} is {2}'.format(num1, num2 ,sub))
mul= float(num1)*float(num2)
print('the mul of {0} and {1} is {2}'.format(num1,num2,mul))
div=float(num1)/float(num2)
print('the div of {0} and {1} is {2}'.format(num1, num2 ,div))